### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mhkarimi** [mhajiloo/persiantools#5]
Collecting persiantools
  Downloading persiantools-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-7vMtxF/persiantools/setup.py", line 14, in <module>
        long_description=readme(),
      File "/tmp/pip-build-7vMtxF/persiantools/setup.py", line 7, in readme
        with open('README.rst', encoding='utf8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7vMtxF/persiantools/

**Comment by mhajiloo** [comment]
Thanks for reporting.
It's Ok now, plz test it.
